# Generated by Django 4.0.2 on 2022-02-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerOrder', '0002_alter_customerorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='orderDate',
            field=models.DateField(auto_now=True),
        ),
    ]
