# Generated by Django 3.2.9 on 2022-02-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(blank=True)),
                ('productId', models.IntegerField()),
                ('quality', models.TextField(max_length=100)),
                ('itemTotal', models.FloatField()),
            ],
            options={
                'db_table': 'OrderItem',
                'ordering': ['-id'],
            },
        ),
    ]
