# Generated by Django 3.2.9 on 2022-02-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'Product',
                'ordering': ['-id'],
            },
        ),
    ]
