# Generated by Django 3.2.9 on 2022-02-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('WHOLESALE', 'WHOLESALE'), ('RETAILER,', 'RETAILER')], max_length=65)),
                ('phone', models.BigIntegerField(max_length=10)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['-id'],
            },
        ),
    ]
