# Generated by Django 4.0.2 on 2022-02-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('WHOLESALE', 'WHOLESALE'), ('RETAILER', 'RETAILER')], max_length=65),
        ),
    ]
